### ISSUE TITLE
Getting HashId Duplicates

### ISSUE THREAD

**Issue by Nemo1234** [ivanakimov/hashids.js#22]
Have a simple code to generate hashIds, but getting multiple duplicates. Is there something wrong with the way I am implementing?

for(int i=100000 ; i < 3000000 ; i ++) {
Hashids hashids = new Hashids(System.currentTimeMillis()+"");
			hashID = hashids.encode(i);
}
There are around 17739 duplicates when I run above code

**Comment by tmorehouse** [comment]
That is because you are using a new salt for each hashid you are generating (the milliseconds).

HashIDs will only be unique if the salt remains the same for each hashid generated.

See closed issue #20 

Change your code to this:

        Hashids hashids = new Hashids(System.currentTimeMillis()+"");
        for(int i=100000 ; i < 3000000 ; i ++) {
            hashID = hashids.encode(i);
        }

And then your generated hashids will be unique.

You should use a static salt value rather than one based on the time, so that future HashIDs will not conflict.
