### ISSUE TITLE
Hash collision when use long secret as salt

### ISSUE THREAD

**Issue by korkeat** [ivanakimov/hashids.js#37]
Hi all,

I found hash collision problem when use Hashids module for generating hash of integer.

The problem happens when:
- Use custom alphabet `ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890`
- Use the long secret string at the beginning with unique strings as salt. For example, `369727d5-d6af-4214-9234-b1b5fa698086XXXXX`, `369727d5-d6af-4214-9234-b1b5fa698086YYYYY`.

It works fine if I put unique strings at the beginning i.e. `XXXXX369727d5-d6af-4214-9234-b1b5fa698086`, `YYYYY369727d5-d6af-4214-9234-b1b5fa698086`. Looks like the module does not use full-length of salt to generate hash.

Here is my environments:
- Hashids v1.1.1 (latest -- August 7th, 2017)
- Node v8.2.1
- macOS Sierra

The full code to test hash collision problem is in this link:
https://gist.github.com/korkeat/7b5ecdcba84865fbd80d257df19ae706

Thank you.

**Comment by zakame** [comment]
Thanks, I seem to be able to reproduce this problem on Hashids.pm as well.

One thing to observe though: your salt (long secret string + unique string) is larger than the alphabet, so I think that is an indicator that your resulting Hashids object state will be taking a salt that's just up to the alphabet (i.e. truncated salt,) hence creating the possibility for collision; this also explains why putting the unique string at the beginning of the salt works, but not the other way around.

I suppose a way to fix this would be to simply constrain salt length to be up to the alphabet length, @ivanakimov what do you think?

**Comment by zakame** [comment]
Digging deeper, I think the root cause for this is on the first `_shuffle()` call, where we pick a character position in the salt (based on both index on the salt as well as the numeric value of the character) to shuffle our alphabet with.  Since the salt is longer than the alphabet, this causes `_shuffle()` to pick positions that "wrap" around the alphabet; this is not so much a problem when the salt is different in the beginning up to the length of the alphabet, but it shows when the salts are otherwise same with only their end being different (and longer than the alphabet.)

My initial fix to add a constraint for `length(salt) <= length(alphabet)` seems to fix this per my testing.

**Comment by korkeat** [comment]
@zakame Thank you for valuable details. So, if you guys fix salt length up to alphabet, it might break my system. However, I will prepare the changes.

BTW, should we update document for limitation to warn other people before using it ?

**Comment by zakame** [comment]
Its up to @ivanakimov though my Perl implementation is ready for changes either way :)

**Comment by ivanakimov** [comment]
Sorry for late response.

Id uniqueness is guaranteed between ids of **one** constructor, not between two different constructors (of course numbers are always going to collide between `hash1` and `hash2` in your example @korkeat).

The problem is that the shuffle function does not work like you'd naturally expect (like `md5` for example). If you change just one character, or add a few at the end like you did, the shuffle is not going to be unique every time. The benefit is it's rather small and fast (look at the code for `md5`).

Next version it will be revisited to see how it can stay small and *if* it can provide better shuffle.
